# Generated by Django 3.2.22 on 2023-11-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupledinput', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupledinputresponse',
            name='block_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coupledinputresponse',
            name='course_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coupledinputresponse',
            name='student_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coupledinputuser',
            name='course_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coupledinputuser',
            name='student_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
